### ISSUE TITLE
Library does not handle HTTP Status Code 429 responses

### ISSUE THREAD

**Issue by iwebsolution** [Vonage/vonage-node-sdk#114]
{ message: 'The API response could not be parsed.',
  parseError:
   SyntaxError: Unexpected end of JSON input
       at Object.parse (native)
       at HttpClient.__parseReponse (/root/node_modules/nexmo/lib/HttpClient.js:127:27)
       at IncomingMessage.<anonymous> (/root/node_modules/nexmo/lib/HttpClient.js:98:19)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickCallback (internal/process/next_tick.js:98:9) }

**Comment by leggetter** [comment]
This seems related to #110. Investigating.

**Comment by leggetter** [comment]
@iwebsolution what's the output from the library if you have `debug` set?

Please remember to remove any mentions of your API Key, Secret or generated JWTs.

**Comment by iwebsolution** [comment]
`
       PS C:\Users\isite\Desktop\Workspace\nexmo> node app.js
       info: Request: { host: 'api.nexmo.com',
         port: 443,
         path: '/v1/calls',
         method: 'POST',
         headers:
          { 'Content-Type': 'application/json',
            Accept: 'application/json',
            'User-Agent': 'nexmo-node/1.2.1 node/6.2.2',
            'Content-Length': 189,
            Authorization: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0OTAwMjM4MTEsImp0aSI6IjFiNGVhZDIwLTBkODItMTFlNy05ODNmLWNkNTEyNjI4Mjc4MSIsIm
       FwcGxpY2F0aW9uX2lkIjoiYjRlNGMzN2UtYjA3OC00ZjkzLWJmMGItYTdjNDgwNTVkNjc5In0.IxxwpnEUPpU2tWJmFvjc70cqoaKZiY8N8X7XTeddRpQTScAtD7xzbIQHsVNYAZQ8zCdKhRmLjHD_N
       ghkSI484DoYDKDqyr4kajo4E-L9brNjky0ABEbeNOg5vDaWKBj0a5pU9Q2LZN_h2lC3HlLOi4mgd8-6Jd9zhxLM2RdgLEAJajviVm7gK_GnoVUKJHePoss9cMp8tZNZTkyYqeyAdUhruAJsok8JxE61
       S7aFmNrTLkQt3Rx2cv0WaS4XE3bfBF5Uc6eAq3_tvB70W-axwel9MutGBBR6mu39YF5XNRmPMH1dQGhPNVqhpdHWKuckqDCBaRBTbUyFfLR8Pe1JkQ' } }
       Body: {"to":[{"type":"phone","number":"40111111111"}],"from":{"type":"phone","number":"40111111111"},"answer_url":["/answer"],"ringing_timer":"25","mac
       hine_detection":"hangup","length_timer":"60"}
       info: Request: { host: 'api.nexmo.com',
       port: 443,
         path: '/v1/calls',
         method: 'POST',
         headers:
          { 'Content-Type': 'application/json',
            Accept: 'application/json',
            'User-Agent': 'nexmo-node/1.2.1 node/6.2.2',
            'Content-Length': 189,
            Authorization: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0OTAwMjM4MTEsImp0aSI6IjFiNTNkZDQwLTBkODItMTFlNy05ODNmLWNkNTEyNjI4Mjc4MSIsIm
       FwcGxpY2F0aW9uX2lkIjoiYjRlNGMzN2UtYjA3OC00ZjkzLWJmMGItYTdjNDgwNTVkNjc5In0.d0h6-2gnGMV7QvcRK2dJhXpnlA46IWCxCYrVWm9XePrboDMMaMP4w1K3IZZcO3xQd7dbTS5S6P9OI
       6RtFwUxdjs2cy29jAaBl-m7uDvhCwzFcdgrK1obJxVZbFaEl91vshhYdC3S1Y1A6XF5b6Tq3CkihoUnJfZPWmgCezkA4Iz-y8ens2suEWIALXFzjShJ3kXtiz1ol9rTxaRUbK0WbaTDNu547u_Fmbj6
       5-9r6k5-SlCrvD0-Wj5lvWGn3890dHK8XNHwlRErbPl3olNdB95UJ-B-yqvSsShjHyEx2K1kV_REKUz18uDmqA7FMi2BceB298XAoU0L1LIQu6twwQ' } }
       Body: {"to":[{"type":"phone","number":"40111111111"}],"from":{"type":"phone","number":"40111111111"},"answer_url":["/answer"],"ringing_timer":"25","mac
       hine_detection":"hangup","length_timer":"60"}
       running on port 80 aka localhost
       info: response ended: 429
       error: SyntaxError: Unexpected end of JSON input
           at Object.parse (native)
           at HttpClient.__parseReponse (C:\Users\isite\Desktop\Workspace\nexmo\node_modules\nexmo\lib\HttpClient.js:127:27)
           at IncomingMessage.<anonymous> (C:\Users\isite\Desktop\Workspace\nexmo\node_modules\nexmo\lib\HttpClient.js:98:19)
           at emitNone (events.js:91:20)
           at IncomingMessage.emit (events.js:185:7)
           at endReadableNT (_stream_readable.js:934:12)
           at _combinedTickCallback (internal/process/next_tick.js:74:11)
           at process._tickCallback (internal/process/next_tick.js:98:9)
       error: could not convert API response to JSON, above error is ignored and raw API response is returned to client
       error: Raw Error message from API
       error: []
       { message: 'The API response could not be parsed.',
         parseError:
          SyntaxError: Unexpected end of JSON input
              at Object.parse (native)
              at HttpClient.__parseReponse (C:\Users\isite\Desktop\Workspace\nexmo\node_modules\nexmo\lib\HttpClient.js:127:27)
              at IncomingMessage.<anonymous> (C:\Users\isite\Desktop\Workspace\nexmo\node_modules\nexmo\lib\HttpClient.js:98:19)
              at emitNone (events.js:91:20)
              at IncomingMessage.emit (events.js:185:7)
              at endReadableNT (_stream_readable.js:934:12)
              at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickCallback (internal/process/next_tick.js:98:9) }
info: response ended: 201
`

**Comment by leggetter** [comment]
This has been fixed in v2.0.0 release https://github.com/Nexmo/nexmo-node/releases/tag/v2.0.0
