### ISSUE TITLE
nexmo.files.get Error: socket hang up

### ISSUE THREAD

**Issue by Nishchit14** [Vonage/vonage-node-sdk#160]
Sometimes file download `nexmo.files.get(fileIdOrUrl, callback);`  request took too much time and endups with below error

```
error: { Error: socket hang up
     at createHangUpError (_http_client.js:329:15)
     at TLSSocket.socketOnEnd (_http_client.js:421:23)
     at emitNone (events.js:110:20)
     at TLSSocket.emit (events.js:207:7)
     at endReadableNT (_stream_readable.js:1056:12)
     at _combinedTickCallback (internal/process/next_tick.js:138:11)
     at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }
```

**Comment by mheap** [comment]
Hi @Nishchit14,

Could you provide any more information to help us reproduce this issue? How large is the file that you were trying to download?

**Comment by Nishchit14** [comment]
@mheap this is the known bug in `http` lib in node.

I have just created the token with this lib and sent a request with [`request`](https://github.com/request/request) lib then it is working good.

**Comment by mheap** [comment]
@Nishchit14 Great! I'll make a note in case it comes up again and will close this issue
