### ISSUE TITLE
"socket hang up" Error when sending SMS

### ISSUE THREAD

**Issue by tbass134** [Vonage/vonage-node-sdk#166]
In a recent project, we use the Nexmo module to create a call and send a SMS sequentially. When trying to send the SMS, we received the following error: ` socket hang up `

The following is the debug log when sending the SMS

```
info: Request: { host: 'rest.nexmo.com', 
Dec 06 08:29:33 fcm-solutions app/web.1:   port: 443, 
Dec 06 08:29:33 fcm-solutions app/web.1:   path: '/sms/json?from=xx&to=xx&text=message&api_key=xxx&api_secret=xx', 
Dec 06 08:29:33 fcm-solutions app/web.1:   method: 'POST', 
Dec 06 08:29:33 fcm-solutions app/web.1:   headers:  
Dec 06 08:29:33 fcm-solutions app/web.1:    { 'Content-Type': 'application/json', 
Dec 06 08:29:33 fcm-solutions app/web.1:      Accept: 'application/json', 
Dec 06 08:29:33 fcm-solutions app/web.1:      'User-Agent': 'nexmo-node/2.0.2 node/8.9.2', 
Dec 06 08:29:33 fcm-solutions app/web.1:      'Content-Length': 155, 
Dec 06 08:29:33 fcm-solutions app/web.1:      Authorization: 'Bearer {token}' } }  
Dec 06 08:29:33 fcm-solutions app/web.1: Body: undefined 
Dec 06 08:31:02 fcm-solutions app/web.1: [2017-12-06T16:31:02.497Z] error: problem with API request detailed stacktrace below  
Dec 06 08:31:02 fcm-solutions app/web.1: [2017-12-06T16:31:02.497Z] error: { Error: socket hang up 
Dec 06 08:31:02 fcm-solutions app/web.1:     at createHangUpError (_http_client.js:331:15) 
Dec 06 08:31:02 fcm-solutions app/web.1:     at TLSSocket.socketOnEnd (_http_client.js:423:23) 
Dec 06 08:31:02 fcm-solutions app/web.1:     at emitNone (events.js:111:20) 
Dec 06 08:31:02 fcm-solutions app/web.1:     at TLSSocket.emit (events.js:208:7) 
Dec 06 08:31:02 fcm-solutions app/web.1:     at endReadableNT (_stream_readable.js:1056:12) 
Dec 06 08:31:02 fcm-solutions app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:138:11) 
Dec 06 08:31:02 fcm-solutions app/web.1:     at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' } 
```

We believe it has something to do with using 2 instances of the Nexmo module, one for VAPI, the other for SMS.

**Comment by AlexLakatos** [comment]
Hi @tbass134, thanks for logging the issue. Can you also post a piece of code so I can try to reproduce this please?
