### ISSUE TITLE
JWT Error while using Channel beta API

### ISSUE THREAD

**Issue by crutchcorn** [Vonage/vonage-node-sdk#300]
The getting started guide for using the Channel API with node says to use the following code:

```javascript
const Nexmo = require('nexmo');

const nexmo = new Nexmo({
  apiKey: 'XXX',
  apiSecret: 'XXX',
});

const message = {
  content: {
    type: 'text',
    text: 'Hello from Vonage',
  },
};

nexmo.channel.send(
  { type: 'sms', number: '19168466876' },
  { type: 'sms', number: '14632165925' },
  message,
  (err, data) => { console.log(data.message_uuid); },
  { useBasicAuth: true },
);
```

However, when trying to use this code in my project I'm shared the following error:

```
Error: cert must be of type Buffer
    at JwtGenerator.generate (C:\Users\crutchcorn\git\Vonage\vonage-phone-verify-notificaitons-app\node_modules\nexmo\lib\JwtGenerator.js:41:15)
    at Credentials.generateJwt (C:\Users\crutchcorn\git\Vonage\vonage-phone-verify-notificaitons-app\node_modules\nexmo\lib\Credentials.js:90:38)
    at HttpClient.post (C:\Users\crutchcorn\git\Vonage\vonage-phone-verify-notificaitons-app\node_modules\nexmo\lib\HttpClient.js:368:65)
    at Channel.send (C:\Users\crutchcorn\git\Vonage\vonage-phone-verify-notificaitons-app\node_modules\nexmo\lib\Channel.js:54:31)
    at C:\Users\crutchcorn\git\Vonage\vonage-phone-verify-notificaitons-app\express\app.js:63:19
    at Layer.handle [as handle_request] (C:\Users\crutchcorn\git\Vonage\vonage-phone-verify-notificaitons-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\crutchcorn\git\Vonage\vonage-phone-verify-notificaitons-app\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\crutchcorn\git\Vonage\vonage-phone-verify-notificaitons-app\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\crutchcorn\git\Vonage\vonage-phone-verify-notificaitons-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\crutchcorn\git\Vonage\vonage-phone-verify-notificaitons-app\node_modules\express\lib\router\index.js:281:22
```

**Comment by AlexLakatos** [comment]
Hi,

Can you reference the link where you found that code snippet, please? It seems it's incomplete, and I'd like to fix the docs for it.
The correct docs for using the Messages API are here: https://developer.nexmo.com/messages/code-snippets/sms/send-sms/node
We've deprecated BasicAuth in the meantime, so you'll need an Application with Messages capabilities for the SDK to work with the API.

**Comment by crutchcorn** [comment]
Oh, okay. That makes things a lot more clear. None of the other docs I was looking at made it clear that it was to use an app, so that clears up things. 

The docs that the code sample comes from is the dashboard code sample: 

https://dashboard.nexmo.com/getting-started/messages

**Comment by kellyjandrews** [comment]
Going to work on getting the dashboard updated for this one - thanks for bringing it up!

**Comment by kellyjandrews** [comment]
This page was replaced with the new sandbox, so no one should see this code snippet. Thanks again!
