### ISSUE TITLE
[BETA] error when fetching paginated results of members

### ISSUE THREAD

**Issue by lukeocodes** [Vonage/vonage-node-sdk#314]
trying to request paginated results of conversation members

```
#!/usr/bin/env node

require('dotenv').config();
const nexmo = require('../utils/nexmo');
const { VONAGE_DEFAULT_CONVERSATION_ID: conversationId } = process.env;

const findAndRemoveOldMembers = (err, res) => {
  const now = new Date().getTime()

  console.log(res._embedded.data.members.length)

  if (res._links.next) {
    getNextPage(res)
  }
}

const pageOpt = { page_size: 100 }

console.log('first page')
nexmo.conversations.members.get(conversationId, pageOpt, findAndRemoveOldMembers)

const getNextPage = (prevPage) => {
  console.log('next page')
  nexmo.conversations.members.next(prevPage, pageOpt, findAndRemoveOldMembers)
}
```

we get a `HttpClient.request` error

```
_http_client.js:173
    throw new ERR_INVALID_ARG_TYPE('method', 'string', method);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "method" argument must be of type string. Received an instance of Object
    at new ClientRequest (_http_client.js:173:11)
    at Object.request (https.js:310:10)
    at HttpClient.request (/Users/luke/Projects/nexmo/poké-chat-server/node_modules/nexmo/lib/HttpClient.js:113:30)
    at Members.get (/Users/luke/Projects/nexmo/poké-chat-server/node_modules/nexmo/lib/Members.js:114:31)
    at Members.next (/Users/luke/Projects/nexmo/poké-chat-server/node_modules/nexmo/lib/Members.js:130:14)
    at getNextPage (/Users/luke/Projects/nexmo/poké-chat-server/bin/cron:41:31)
    at findAndRemoveOldMembers (/Users/luke/Projects/nexmo/poké-chat-server/bin/cron:30:5)
    at HttpClient.__parseResponse (/Users/luke/Projects/nexmo/poké-chat-server/node_modules/nexmo/lib/HttpClient.js:232:9)
    at IncomingMessage.<anonymous> (/Users/luke/Projects/nexmo/poké-chat-server/node_modules/nexmo/lib/HttpClient.js:141:19)
    at IncomingMessage.emit (events.js:333:22) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by kellyjandrews** [comment]
Thanks @lukeocodes I'll take a look.

**Comment by lukeocodes** [comment]
This is totally an implementation issue and it's right there in my code.

```nexmo.conversations.members.next(prevPage, pageOpt, findAndRemoveOldMembers)```

should be

```nexmo.conversations.members.next(prevPage, pageOpt, findAndRemoveOldMembers)```

**Comment by lukeocodes** [comment]
This is totally an implementation issue and it's right there in my code.

```nexmo.conversations.members.next(prevPage, pageOpt, cb)```

should be

```nexmo.conversations.members.next(prevPage, cb)```

**Comment by kellyjandrews** [comment]
Thanks for letting me know @lukeocodes
